[client]
showErrorDetails = true

[server]
port = 8501
enableXsrfProtection = true

[theme]
primaryColor = "#00f2ff"
backgroundColor = "#050505"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#ffffff"
font = "monospace"

[logger]
level = "info"
